name: Deploy-UAT

# Controls when the workflow will run
on:
  push:
    branches:
      - 'Release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      whatIf:
        description: 'Enable WhatIf Mode'
        type: boolean
        required: true
        default: true

env:
  PROFILE: Contoso

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: UAT
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:1.0.0-rc.2_20220525

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: pbi-tools info
        run: |
          /app/pbi-tools/pbi-tools.core info

      - name: pbi-tools deploy (WhatIf)
        if: ${{ github.event.inputs.whatIf == 'true' }}
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" UAT -whatIf
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}

      - name: pbi-tools deploy
        if: ${{ github.event.inputs.whatIf != 'true' }}
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" UAT
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
